# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\change_grid_size_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(478, 97)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label1 = QtWidgets.QLabel(Dialog)
        self.label1.setObjectName("label1")
        self.horizontalLayout.addWidget(self.label1)
        self.inputWidth = QtWidgets.QLineEdit(Dialog)
        self.inputWidth.setObjectName("inputWidth")
        self.horizontalLayout.addWidget(self.inputWidth)
        self.label2 = QtWidgets.QLabel(Dialog)
        self.label2.setObjectName("label2")
        self.horizontalLayout.addWidget(self.label2)
        self.inputHeight = QtWidgets.QLineEdit(Dialog)
        self.inputHeight.setObjectName("inputHeight")
        self.horizontalLayout.addWidget(self.inputHeight)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBoxApplyToAll = QtWidgets.QCheckBox(Dialog)
        self.checkBoxApplyToAll.setObjectName("checkBoxApplyToAll")
        self.horizontalLayout_2.addWidget(self.checkBoxApplyToAll)
        self.pushButtonOk = QtWidgets.QPushButton(Dialog)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.horizontalLayout_2.addWidget(self.pushButtonOk, 0, QtCore.Qt.AlignRight)
        self.pushButtonCancel = QtWidgets.QPushButton(Dialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label1.setText(_translate("Dialog", "Введите размер сетки:"))
        self.inputWidth.setPlaceholderText(_translate("Dialog", "Ширина"))
        self.label2.setText(_translate("Dialog", "x"))
        self.inputHeight.setPlaceholderText(_translate("Dialog", "Высота"))
        self.checkBoxApplyToAll.setText(_translate("Dialog", "Применить ко всем сеткам"))
        self.pushButtonOk.setText(_translate("Dialog", "Применить"))
        self.pushButtonCancel.setText(_translate("Dialog", "Отмена"))
