# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\change_grid_size_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeGridCellSizeDialog(object):
    def setupUi(self, ChangeGridCellSizeDialog):
        ChangeGridCellSizeDialog.setObjectName("ChangeGridCellSizeDialog")
        ChangeGridCellSizeDialog.resize(485, 164)
        self.verticalLayout = QtWidgets.QVBoxLayout(ChangeGridCellSizeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label3 = QtWidgets.QLabel(ChangeGridCellSizeDialog)
        self.label3.setObjectName("label3")
        self.horizontalLayout_3.addWidget(self.label3)
        self.labelGridSize = QtWidgets.QLabel(ChangeGridCellSizeDialog)
        self.labelGridSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelGridSize.setObjectName("labelGridSize")
        self.horizontalLayout_3.addWidget(self.labelGridSize)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label1 = QtWidgets.QLabel(ChangeGridCellSizeDialog)
        self.label1.setObjectName("label1")
        self.horizontalLayout.addWidget(self.label1)
        self.inputWidth = QtWidgets.QLineEdit(ChangeGridCellSizeDialog)
        self.inputWidth.setObjectName("inputWidth")
        self.horizontalLayout.addWidget(self.inputWidth)
        self.label2 = QtWidgets.QLabel(ChangeGridCellSizeDialog)
        self.label2.setObjectName("label2")
        self.horizontalLayout.addWidget(self.label2)
        self.inputHeight = QtWidgets.QLineEdit(ChangeGridCellSizeDialog)
        self.inputHeight.setObjectName("inputHeight")
        self.horizontalLayout.addWidget(self.inputHeight)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBoxApplyToAll = QtWidgets.QCheckBox(ChangeGridCellSizeDialog)
        self.checkBoxApplyToAll.setObjectName("checkBoxApplyToAll")
        self.horizontalLayout_2.addWidget(self.checkBoxApplyToAll)
        self.pushButtonOk = QtWidgets.QPushButton(ChangeGridCellSizeDialog)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.horizontalLayout_2.addWidget(self.pushButtonOk, 0, QtCore.Qt.AlignRight)
        self.pushButtonCancel = QtWidgets.QPushButton(ChangeGridCellSizeDialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ChangeGridCellSizeDialog)
        QtCore.QMetaObject.connectSlotsByName(ChangeGridCellSizeDialog)

    def retranslateUi(self, ChangeGridCellSizeDialog):
        _translate = QtCore.QCoreApplication.translate
        ChangeGridCellSizeDialog.setWindowTitle(_translate("ChangeGridCellSizeDialog", "Изменить размер клетки сетки"))
        self.label3.setText(_translate("ChangeGridCellSizeDialog", "Размер сетки:"))
        self.labelGridSize.setText(_translate("ChangeGridCellSizeDialog", "1920x1080"))
        self.label1.setText(_translate("ChangeGridCellSizeDialog", "Введите размер клетки:"))
        self.inputWidth.setPlaceholderText(_translate("ChangeGridCellSizeDialog", "Ширина (пикс.)"))
        self.label2.setText(_translate("ChangeGridCellSizeDialog", "x"))
        self.inputHeight.setPlaceholderText(_translate("ChangeGridCellSizeDialog", "Высота (пикс.)"))
        self.checkBoxApplyToAll.setText(_translate("ChangeGridCellSizeDialog", "Применить ко всем сеткам"))
        self.pushButtonOk.setText(_translate("ChangeGridCellSizeDialog", "Применить"))
        self.pushButtonCancel.setText(_translate("ChangeGridCellSizeDialog", "Отмена"))
